MOVIE_LIST = [{'Title': "Schindler's List",
               'Plot': "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
               'Poster': "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL50_SY1000_CR0,0,666,1000_AL_.jpg",
               'Trailer': "https://youtu.be/mxphAlJID9U"},
              {'Title': 'The Godfather',
               'Plot': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL50_SY1000_CR0,0,704,1000_AL_.jpg',
               'Trailer': 'https://youtu.be/NmzuHjWmXOc'},
              {'Title': 'Waking Life',
               'Plot': 'A man shuffles through a dream meeting various people and discussing the meanings and purposes of the universe.',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMWM0ZjY5ZjctODNkZi00Nzk0LWE1ODUtNGM4ZDUyMzUwMGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/SbPgprcMtjo'},
              {'Title': 'Incendies',
               'Plot': 'Twins journey to the Middle East to discover their family history and fulfill their mother\'s last wishes.',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BZTViOTVkOTAtYzljZS00YjQyLTlhNDMtYTExMGE2YmYxMWE5XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/0nycksytL1A'},
              {'Title': 'Dazed and Confused',
               'Plot': 'The adventures of high school and junior high students on the last day of school in May 1976.',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMTM5MDY5MDQyOV5BMl5BanBnXkFtZTgwMzM3NzMxMDE@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/3aQuvPlcB-8'},
              {'Title': 'The Shawshank Redemption',
               'Plot': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/NmzuHjWmXOc'}]
