# List of movie details.
MOVIE_LIST = [{'Title': "Schindler's List",
               'Plot': "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
               'Released': '4 February 1994',
               'Rating': 'R',
               'Genre': 'Biography, Drama, History',
               'Poster': "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL50_SY1000_CR0,0,666,1000_AL_.jpg",
               'Trailer': "https://youtu.be/mxphAlJID9U", },
              {'Title': 'The Godfather',
               'Plot': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
               'Released': '24 March 1972',
               'Rating': 'R',
               'Genre': 'Crime, Drama',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BNTc0ZDk1YWItZDZiNi00NTdmLWE0MDctNTVhYTRhMDBmZjNjXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/mxphAlJID9U'},
              {'Title': 'Waking Life',
               'Plot': 'A man shuffles through a dream meeting various people and discussing the meanings and purposes of the universe.',
               'Released': '7 March 2002 ',
               'Rating': 'R',
               'Genre': 'Animation, Drama, Fantasy',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMWM0ZjY5ZjctODNkZi00Nzk0LWE1ODUtNGM4ZDUyMzUwMGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/SbPgprcMtjo'},
              {'Title': 'Incendies',
               'Plot': 'Twins journey to the Middle East to discover their family history and fulfill their mother\'s last wishes.',
               'Released': '12 January 2011',
               'Rating': 'R',
               'Genre': 'Drama, Mystery, War',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BZTViOTVkOTAtYzljZS00YjQyLTlhNDMtYTExMGE2YmYxMWE5XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/0nycksytL1A'},
              {'Title': 'Dazed and Confused',
               'Plot': 'The adventures of high school and junior high students on the last day of school in May 1976.',
               'Released': '10 February 1994',
               'Rating': 'R',
               'Genre': 'Comedy',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMTM5MDY5MDQyOV5BMl5BanBnXkFtZTgwMzM3NzMxMDE@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/3aQuvPlcB-8'},
              {'Title': 'The Shawshank Redemption',
               'Plot': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
               'Released': '14 October 1994',
               'Rating': 'R',
               'Genre': 'Drama',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_QL50_.jpg',
               'Trailer': 'https://youtu.be/NmzuHjWmXOc'},
              {'Title': 'Midnight in Paris',
               'Plot': 'While on a trip to Paris with his fiancée\'s family, a nostalgic screenwriter finds himself mysteriously going back to the 1920s everyday at midnight.',
               'Released': '10 June 2011',
               'Rating': 'PG-13',
               'Genre': 'Comedy, Fantasy, Romance',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMTM4NjY1MDQwMl5BMl5BanBnXkFtZTcwNTI3Njg3NA@@._V1_QL50_SY1000_CR0,0,677,1000_AL_.jpg',
               'Trailer': 'https://youtu.be/FAfR8omt-CY'},
              {'Title': '12 Angry Men',
               'Plot': 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
               'Released': '10 April 1957',
               'Rating': 'NR',
               'Genre': 'Drama',
               'Poster': 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_QL50_SY1000_CR0,0,649,1000_AL_.jpg',
               'Trailer': 'https://youtu.be/_13J_9B5jEk'},
              {'Title': 'Taxi Driver',
                  'Plot': 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.',
                  'Released': '8 February 1976',
                  'Rating': 'R',
                  'Genre': 'Crime, Drama',
                  'Poster': 'https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_QL50_SY1000_CR0,0,658,1000_AL_.jpg',
                  'Trailer': 'https://youtu.be/UUxD4-dEzn0'}]
